Use base 64 encoding instead of uri encoding of state param for yahoo
MrSwitch/hello.js pull request #658
Opened 2022-10-12 04:20 UTC by arushi364

2022-10-12 04:26 UTC, arushi364 commented
Yahoo expects base 64 encoding of state param and somehow fails at the consent page if URI encoding is used. This PR intends to change the encoding for Yahoo network. It retains the original behavior for other networks.

For all clients using hellojs for yahoo (not sure if there are any as it seemed busted for yahoo), one will have to base 64 decode the state param before it can be parsed to extract the state param attributes.

2022-10-12 20:57 UTC, arushi364 commented
@MrSwitch could you please take a look at the changes ?

2022-10-16 19:47 UTC, MrSwitch commented
Hi @arushi364 

That logic should be defined in the yahoo module. As such i can't merge this as is.

2022-10-16 20:43 UTC, arushi364 commented
> Hi @arushi364
> 
> That logic should be defined in the yahoo module. As such i can't merge this as is.

@MrSwitch Thanks for replying back. I tried changing the encoding in the login function. But, once the state param is base 64 encoded in the yahoo login function, the code in hello.js tries to again uri encode it after stringifying the state. The base 64 encoded state does not change when uri encoded, but the problem here is JSON.stringify results in adding quotes in the state param which is eventually converted to %22, which makes yahoo unhappy.

state param in yahoo login function: <base64 encoded string>
hello.js transitions it to: 
JSON.stringify: "<base64 encoded string>"
encodeURIComponent : %22<base64 encoded string>%22

This is the code which does the transition and is executed after the provider.login function is executed. 

[// Convert state to a string
		p.qs.state = encodeURIComponent(JSON.stringify(p.qs.state)); [https://github.com/MrSwitch/hello.js/blob/master/src/hello.js#:~:text=//%20Convert%20state%20to,))%3B](url)

Any suggestions on how can I avoid adding quotes here so that no uri encoded characters are added in the state?

2022-11-11 07:14 UTC, arushi364 commented
@MrSwitch Wondering if you got a chance to look at my previous comment? Could you please advise with the next step? We really need to fix this library so that we can consume this for talking to Yahoo.

2022-11-14 18:49 UTC, MrSwitch commented
Can you create a property like `provider.oauth.base64State` define this to `true` on just the Yahoo module?

Also to make it easier to merge:

1. Write tests where appropriate
2. Document the new property

Thankyou 👍

2023-01-06 19:45 UTC, arushi364 commented
Thanks @MrSwitch. Just wanted to confirm, to create a new property provider.oauth.base64State, I would need to update the HelloJSOAuthDef in this file?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hellojs/index.d.ts

2023-01-11 02:30 UTC, arushi364 commented
@MrSwitch I have added a new property and updated the test cases. Could you please take a look at the changes?

2023-01-13 18:35 UTC, arushi364 commented
@MrSwitch Could you please take a look at the PR?

2023-01-18 19:08 UTC, arushi364 commented
Gentle ping! @MrSwitch

2023-01-24 03:40 UTC, arushi364 commented
@MrSwitch Could please take a look at the changes? We are waiting on merging this fix so that we can consume the library for adding a yahoo account in our App. I would highly appreciate if you could review the changes once?

2023-01-24 07:33 UTC, MrSwitch requested changes
Looks fantastic

Only change is that individual module handling should not belong in the core, or indeed any reference too. So i've removed the yahoo specific reference from the core tests.

2023-01-24 07:33 UTC, MrSwitch commented on tests/specs/unit/core/hello.login.js
> +		});
```suggestion
		it('should uri encode the state by default', function(done) {

			var spy = sinon.spy(function(url, name, optins) {
				// The url should contain uri encoded characters
				expect(url).to.contain('state=%7B%22');

				done();
			});

			utils.popup = spy;

			hello.login('testable');
		});
```

2023-01-24 07:33 UTC, MrSwitch commented on tests/specs/unit/core/hello.login.js
> +		});
```suggestion
		it('should uri encode the state if oauth.base64_state is false', function(done) {

			hello.services.testable.oauth.base64_state = false;

			var spy = sinon.spy(function(url, name, optins) {
				// The url should contain uri encoded characters
				expect(url).to.contain('state=%7B%22');

				done();
			});

			utils.popup = spy;

			hello.login('testable');
		});
```

2023-01-24 07:33 UTC, MrSwitch commented on tests/specs/unit/core/hello.login.js
> +		});
```suggestion
		it('should base 64 encode the state if oauth.base64_state is true', function(done) {

			hello.services.testable.oauth.base64_state = true;

			var spy = sinon.spy(function(url, name, optins) {
				// The url should not contain uri encoded characters
				expect(url).to.not.contain('state=%7B%22');

				done();
			});

			utils.popup = spy;

			hello.login('testable');
		});
```

2023-01-24 07:33 UTC, MrSwitch commented on tests/specs/unit/core/hello.login.js
> +		});
We dont define individual module settings here...

```suggestion
```

But the other tests are great 👍

2023-01-24 07:34 UTC, MrSwitch commented
> @MrSwitch Could please take a look at the changes? We are waiting on merging this fix so that we can consume the library for adding a yahoo account in our App. I would highly appreciate if you could review the changes once?

Looks great, thank you for persevering 🙏

2023-01-24 09:25 UTC, arushi364 commented
Thanks @MrSwitch I have addressed the review comments. Could you please take a look?

2023-01-24 23:23 UTC, MrSwitch approved these changes
LGTM 🎉

2023-01-24 23:24 UTC, merged

2023-07-27 13:51 UTC, ioliva commented
@MrSwitch , @arushi364 I have been having problems using this new `base64_state` property.

I have found that, afterwards, in the responseHandler, the "Could not decode state" error is raised, since the base64 encoded state should be decoded again.

So, I request reopening this issue in order to complete the fix (I will pass PR).